# Generated by Django 2.2.3 on 2019-07-14 23:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=5)),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='states', to='addresses.Country')),
            ],
            options={
                'verbose_name': 'state',
                'verbose_name_plural': 'states',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=5)),
                ('state', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cities', to='addresses.State')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('line1', models.CharField(blank=True, max_length=100)),
                ('line2', models.CharField(blank=True, max_length=100, null=True)),
                ('suite', models.CharField(blank=True, max_length=10, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address_type', models.CharField(blank=True, choices=[('Billing', 'Billing'), ('Business', 'Business'), ('Primary', 'Primary'), ('Shipping', 'Shipping')], max_length=11)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', to='addresses.City')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
