# Generated by Django 2.2.3 on 2019-07-14 23:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('required', models.BooleanField(blank=True, default=False)),
                ('skill', models.CharField(blank=True, max_length=255)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='accounts.Employer')),
            ],
            options={
                'verbose_name': 'competency',
                'verbose_name_plural': 'competencies',
            },
        ),
        migrations.CreateModel(
            name='CompetencyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('tier', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalCompetency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(blank=True, max_length=10, null=True)),
                ('experience', models.CharField(blank=True, max_length=10, null=True)),
                ('competency', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional', to='competencies.Competency')),
                ('professional', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='accounts.Professional')),
            ],
        ),
        migrations.CreateModel(
            name='JobQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(blank=True, max_length=10, null=True)),
                ('experience', models.CharField(blank=True, max_length=10, null=True)),
                ('is_required', models.BooleanField(blank=True, default=False)),
                ('competency', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='competencies.Competency')),
                ('job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifictions', to='jobs.Job')),
            ],
        ),
        migrations.AddField(
            model_name='competency',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='competencies.CompetencyType'),
        ),
    ]
